[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinker.ld"]
runner = "qemu-system-riscv32 -machine sifive_e -bios none -display none -serial stdio -S -s -kernel"
